name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.100

    - name: Build assembly
      run: dotnet build source/CloudNative.CloudEvents.Experimental.Endpoints.sln

    - name: Create binary release
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet publish source/CloudNative.CloudEvents.Experimental.Endpoints.sln --configuration Release --output bin/Release --framework net6.0
    
    - name: Publish   
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: bin/Release